skillMetadata:
  sections:
    - name: Updates
      fields:
        - name: notify_updates
          type: checkbox
          label: Notify when updates are available
          value: True
        - name: include_prerelease
          type: checkbox
          label: Include pre-releases in update checks
          value: False
    - name: Image Creation
      fields:
        - name: image_url
          type: text
          label: URL of image to download
          value: ""
        - name: image_drive
          type: text
          label: Default drive to install images to
          value: "/dev/sdb"